#!/bin/bash

echo "Enter File name :"
read FileName


echo -e "#include <stdio.h>">${FileName}
echo -e "#include \"main.h\"">>${FileName}
echo -e "#include <stdlib.h>\n">>${FileName}

echo -e "/**
* - 
*
*Return: Always 0 (Sucess)
*/\n">>${FileName}


echo -e "int main(void)
{
	return (0);
}">>${FileName}

chmod +x ${FileName}
