#!/bin/bash

echo "Enter File name :"
read FileName


echo -e "#include <stdio.h>">${FileName}

echo -e "
/**
*main - print the prgram name
*@argc: integer == the count of program arguments
*@argv: array of pointers to strings (the program arguments)
*Return: Always 0 (Success)
*/">>$FileName



echo -e "int main(int argc, char *argv[])
{
	return (0);
}">>${FileName}

chmod +x ${FileName}
